package com.ebay.sdk.okhttp

import okhttp3.OkHttpClient
import org.mockserver.integration.ClientAndServer
import java.net.InetSocketAddress
import java.net.Proxy
import java.security.SecureRandom
import java.security.cert.X509Certificate
import javax.net.ssl.SSLContext
import javax.net.ssl.TrustManager
import javax.net.ssl.X509TrustManager

class TestClientFactory {
    companion object {
        /**
         * This creates a client that acts as a proxy to intercept calls that match a certain
         * expectation to be defined in a unit test without modifying any of the client code.  The
         * alternative would be to allow for a "test-only" URL in the SDK which is an extremely
         * bad practice.
         *
         * This should only be used for testing purposes.
         *
         * Code generated by Gemini.
         */
        fun create(builder : OkHttpClient.Builder, mockClientAndServer : ClientAndServer) : OkHttpClient {
            // Create an insecure TrustManager to make OkHttp trust MockServer's self-signed SSL
            val trustAllCerts = object : X509TrustManager {
                override fun checkClientTrusted(chain: Array<out X509Certificate>?, authType: String?) {}
                override fun checkServerTrusted(chain: Array<out X509Certificate>?, authType: String?) {}
                override fun getAcceptedIssuers(): Array<X509Certificate> = arrayOf()
            }
            val sslContext = SSLContext.getInstance("SSL").apply {
                init(null, arrayOf<TrustManager>(trustAllCerts), SecureRandom())
            }

            // Take a builder and add stuff that will make it suitable for use in unit tests
            return builder
                // Explicitly force this specific client instance to route through local MockServer
                // Host is not exposed in ClientAndServer, but it always runs locally and therefore it's safe to hardcode as localhost
                .proxy(Proxy(Proxy.Type.HTTP, InetSocketAddress("localhost", mockClientAndServer.port)))
                // Trust MockServer's local SSL certificates
                .sslSocketFactory(sslContext.socketFactory, trustAllCerts)
                .build()
        }
    }
}