plugins {
    `java-library`
    `maven-publish`
}

/* These tasks delegate off to Maven.  The initial reason for this was the difficulty of getting
   existing wsimport Gradle plugins for various reasons (lack of Kotlin code samples, inability to
   work with Web WSDL).  This allows for a working Maven configuration to be used.  Some additional
   steps are needed to needed to make artifacts generated by Maven available to Gradle and these
   steps will be noted in documentation.
 */
tasks.register<Exec>("mvnCleanDelegate") {
    commandLine("bash", "-c", """"mvn clean -Debay-api.version=${gradle.extra["ebayApiVersion"]}"""")
}

tasks.register<Exec>("mvnInstallDelegate") {
    commandLine("bash", "-c", """"mvn install -Debay-api.version=${gradle.extra["ebayApiVersion"]}"""")
}

tasks.getByName("clean") {
    dependsOn("mvnCleanDelegate")
}

tasks.getByName("publishToMavenLocal") {
    dependsOn("mvnInstallDelegate")
}