#!/usr/bin/env bash

calendar_to_instant() {
    xargs sed -i \
        -e "s/java\.util\.Calendar/java.time.Instant/g" \
        -e "s/Calendar/Instant/g"
}

if [[ "$(basename "$0")" == "restructure.sh" ]]; then
    cleanup() {
        # come back to this directory
        cd $pwd
    }

    # clear out everything and point to the desired branch
    reset_repo() {
        cd $1
        git restore --staged .
        git checkout .
        git clean -fd
        git checkout main
        cd $pwd
    }

    trap cleanup EXIT

    pwd=`pwd`
    target=$1
    api_version=$2

    reset_repo $target

    # easier to move to the target repo and restore after instead of staying in this repo because specifying the target 
    # directory in for each app (git, mvn, etc if it can be specified at all)
    # cd $target && reset_repo $branch
    pids_core=()
    (cd $target/source/core/src && 
        mkdir -p $target/trading-api-sdkcore/src/main/java && 
        cp -r --parents . $target/trading-api-sdkcore/src/main/java) & pids_core+=($!)
    (cd $target/source/apiCalls/src && 
        mkdir -p $target/trading-api-version/1331/src/main/java &&
        cp -r --parents . $target/trading-api-version/1331/src/main/java) & pids_core+=($!)
    (cd $target/source/helper/src && 
        mkdir -p $target/trading-api-version/1331/src/main/java &&
        cp -r --parents . $target/trading-api-version/1331/src/main/java) & pids_core+=($!)
    wait $pids_core

    for file in `git ls-files -cmo`; do
        if [[ "$file" == ".gitignore" ]]; then
            echo "skipping $file"
        elif [[ "$file" == "gitignore" ]]; then
            cat $file >> $target/.gitignore
        else
            cp --parents $file $target
        fi
    done

    # exception handling - The purpose of each transformation should be documented explicitly.

    ## These classes came packaged with the original repository but this is no longer needed because they are
    ## autogenerated from trading-api-eBLBaseComponents.
    rm -rf $target/trading-api-sdkcore/src/main/java/com/ebay/soap
    ## Temporarily remove anything related to Java AWT + Swing from sdkcore in order to focus first on the API.  API 
    ## and UI components should be compiled and packaged separately.  Catches import statements but any fully-qualified 
    ## references will need to be addressed individually.
    cp --parents trading-api-sdkcore/src/main/java/com/ebay/sdk/ApiCall.java \
        trading-api-sdkcore/src/main/java/com/ebay/sdk/ApiCredential.java \
        $target
    find $target/trading-api-sdkcore -name *.java | 
        xargs grep -l -e "^import java\.awt\..*;$" -e  "^import javax\.swing\..*;$" | 
        xargs rm
    ## This file doesn't follow the Java packaging convention and therefore it is moved to conform to it.
    mkdir -p $target/trading-api-version/1331/src/main/java/com/ebay/sdk/helper/ui && \
    cp $target/source/core/src/DialogFetchToken.java \
        $target/trading-api-version/1331/src/main/java/com/ebay/sdk/helper/ui

    ## Convert from javax.xml to jakarta.xml because the former is not packaged for JDK9+.  Fortunately this works
    ## because the imports follow a consistent spacing format but this is very flaky.  An AST approach like OpenRewrite
    ## would have been preferred but it does not fit this use case.
    find $target/trading-api-* -type f -name *.java |
    xargs sed -i \
        -e "s/^import javax\.xml\.ws/import jakarta.xml.ws/" \
        -e "s/^import javax\.xml\.soap/import jakarta.xml.soap/" \
        -e "s/^import javax\.xml\.bind/import jakarta.xml.bind/"
    ## Modernize TimeFilter by moving from java.util to java.time
    echo "$target/trading-api-sdkcore/src/main/java/com/ebay/sdk/TimeFilter.java" | calendar_to_instant
    find $target/trading-api-version/1331/src/main/java/com/ebay/sdk/call -type f -name *.java | calendar_to_instant

    # build
    cd $target && ./gradlew --stacktrace --info clean publishToMavenLocal -PebayApiVersion=$2
    cd $pwd
fi